namespace BaronDesk.Shared.Contracts;

/// <summary>
/// Payload sent by the agent during the one-time enrollment handshake.
/// Contains the bootstrap token (provisioned by the admin) and machine metadata.
/// </summary>
public sealed record EnrollmentRequest
{
    /// <summary>
    /// One-time bootstrap token generated by the admin dashboard.
    /// </summary>
    public string BootstrapToken { get; init; } = string.Empty;

    /// <summary>
    /// Windows machine name (Environment.MachineName).
    /// </summary>
    public string MachineName { get; init; } = string.Empty;

    /// <summary>
    /// Station serial number from configuration.
    /// </summary>
    public string SerialNumber { get; init; } = string.Empty;

    /// <summary>
    /// OS version string (Environment.OSVersion).
    /// </summary>
    public string OsVersion { get; init; } = string.Empty;

    /// <summary>
    /// Agent software version.
    /// </summary>
    public string AgentVersion { get; init; } = "1.0.0";
}
