namespace BaronDesk.Shared.Contracts;

/// <summary>
/// Body of <c>POST /enrollment/request</c>: the station's first contact with the backend (Auth &amp; Security AS1).
/// </summary>
/// <remarks>
/// FROZEN (Step 0 §2): <see cref="OneTimeToken"/>, <see cref="Mac"/>, <see cref="Ip"/>.
/// OPEN (skill §15 item 8), confirm with backend member C: the remaining fields. <see cref="AgentPublicKey"/> fills
/// the required <c>Machine.agentPublicKey</c> column, and <see cref="Signature"/> proves the station holds the matching
/// private key. The agent re-sends the same request (same key) while the answer is <c>PENDING</c>; the backend must
/// release the station token only to a request signed by the key it recorded first, with a newer <see cref="SignedAt"/>.
/// </remarks>
public sealed record EnrollmentRequest
{
    /// <summary>One-time token generated by an admin in the dashboard. Never logged.</summary>
    public required string OneTimeToken { get; init; }

    /// <summary>MAC address of the interface that reaches the server (informational: MAC is not authentication).</summary>
    public required string Mac { get; init; }

    public required string Ip { get; init; }

    /// <summary>The station's identity handle (<c>Machine.serialNumber</c>), also sent in every <c>handshake</c>.</summary>
    public required string SerialNumber { get; init; }

    public required string MachineName { get; init; }

    public required string AgentVersion { get; init; }

    /// <summary>Base64 DER SubjectPublicKeyInfo of the station's ECDSA P-256 key.</summary>
    public required string AgentPublicKey { get; init; }

    /// <summary>ISO-8601 time the request was signed, exactly as covered by <see cref="Signature"/>.</summary>
    public required string SignedAt { get; init; }

    /// <summary>
    /// Base64 DER ECDSA-SHA256 signature over the UTF-8 lines
    /// <c>BARONDESK-ENROLL-V1, oneTimeToken, serialNumber, mac, ip, agentPublicKey, signedAt</c> joined with <c>\n</c>.
    /// </summary>
    public required string Signature { get; init; }
}

/// <summary>
/// Answer to <c>POST /enrollment/request</c>. FROZEN: <c>{ status: "PENDING" }</c>; the other fields are OPEN
/// (skill §15 item 8), confirm with backend member C.
/// </summary>
public sealed record EnrollmentResponse
{
    /// <summary>One of <see cref="EnrollmentStatuses"/>.</summary>
    public required string Status { get; init; }

    /// <summary>The long-lived station JWT, present only when <see cref="Status"/> is <c>ENROLLED</c>.</summary>
    public string? StationToken { get; init; }

    public string? MachineId { get; init; }

    /// <summary>Why the enrollment was rejected (shown in the agent log).</summary>
    public string? Reason { get; init; }
}

public static class EnrollmentStatuses
{
    /// <summary>Waiting for an admin to approve the station in the dashboard.</summary>
    public const string Pending = "PENDING";

    public const string Enrolled = "ENROLLED";

    /// <summary>Token invalid/expired or the admin declined. The token is spent; a new one must be provisioned.</summary>
    public const string Rejected = "REJECTED";
}
